description: AI-Powered Content Generator (Fullstack & Scalable)
globs:
  - "**/*.{ts,tsx,js,jsx}"
  - "**/*.{yml,yaml}"
  - "**/*.{md,mdx}"
  - "**/*.{json,env}"
  - "**/*.{dockerfile,docker-compose.yml}"
alwaysApply: true

requirements:
  frontend:
    framework: "React + Next.js"
    ui: "ShadCN UI"
    features:
      - "User Authentication (JWT/OAuth)"
      - "Dashboard with topic/style input"
      - "AI blog post generation"
      - "Draft editing and saving"
      - "Post history view"
      - "Public post sharing"
      - "React Query/SWR for API"

  backend:
    framework: "Node.js + Express/Fastify/NestJS"
    database: "PostgreSQL/MongoDB/Firebase"
    api:
      endpoints:
        - "POST /auth/signup"
        - "POST /auth/login"
        - "POST /generate"
        - "POST /posts/save"
        - "GET /posts/user"
        - "GET /posts/:id"
      features:
        - "Rate limiting"
        - "Error handling"
        - "Logging"

  deployment:
    containerization: "Docker"
    orchestration: "Docker Compose"
    cloud: "Vercel/AWS/Render"
    scaling: "Auto-scaling"
    caching: "Redis/Cloudflare"

  documentation:
    required: true
    sections:
      - "Architecture Overview"
      - "Tech Stack & Choices"
      - "Deployment Strategy"
      - "Challenges & Solutions"
      - "Improvements & Next Steps"

  submission:
    requirements:
      - "GitHub repository"
      - "README.md with setup"
      - "Live demo link"
      - "Technical documentation" 