@api=http://localhost:4000/api
@firstname=Iliya
@lastname=Brook
@password=123456
@email=iliyabrook1987@gmail.com
@role=admin

### REGISTRATION
# @name signup
POST {{api}}/users/sign-up
Content-Type: application/json

{
	"email": "{email}}",
	"firstname": "{{firstname}}",
	"lastname": "{{lastname}}",
    "password" : "{{password}}"
}

### LOGIN
# @name login
POST {{api}}/users/sign-in
Content-Type: application/json

{
	"email": "{{email}}",
    "password" : "{{password}}"
}


### Check auth
GET {{api}}/users/auth
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

### GET ALL USERS
GET {{api}}/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

### GET ALL USERS WITH LIMIT
GET {{api}}/users?limit=1&page=1
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

### REFRESH
# @name refresh
GET {{api}}/users/refresh
Content-Type: application/json

### LOGOUT
POST {{api}}/users/sign-out
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

### Admin route patch update
@updateId=67dad847466b3c04a69c7de3
PATCH {{api}}/users/{{updateId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
	"firstname": "FirstNameUpdated44"
}

### Generate Post
# Requires authentication
POST {{api}}/posts/generate
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "topic": "Latest advancements in AI",
  "style": "informative and slightly informal"
}