name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          
      - name: Debug SSH connection with verbose output
        run: |
          echo "Debugging SSH connection..."
          echo "Setting up SSH config with verbose logging"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          echo "LogLevel DEBUG3" >> ~/.ssh/config
          
          # Connection attempt
          echo "Testing SSH connection to 157.180.25.1"
          timeout 10 ssh -v root@157.180.25.1 "echo 'Connection successful'" || echo "Connection timed out"

      - name: Create root .env file
        run: |
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" > .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          
      - name: Set Server IP manually
        run: |
          echo "Setting SERVER_IP manually to 157.180.25.1"
          echo "SERVER_IP=157.180.25.1" >> $GITHUB_ENV
          
      - name: Create frontend .env.production file
        run: |
          echo "NEXT_PUBLIC_API_URL=http://157.180.25.1:${{ secrets.SERVER_PORT }}/api" > frontend/.env.production
          
      - name: Install Docker on server (if needed)
        run: |
          echo "Installing Docker on server 157.180.25.1..."
          ssh root@157.180.25.1 "if ! command -v docker &> /dev/null; then apt update && apt install -y docker.io docker-compose && systemctl enable docker && systemctl start docker; fi"
          
      - name: Deploy to Hetzner with detailed logging
        run: |
          echo "Deploying to server 157.180.25.1..."
          
          # Create project directory with verbose output
          echo "Creating project directory..."
          ssh -o StrictHostKeyChecking=no root@157.180.25.1 "mkdir -p /root/sokal-ai-generate"
          
          # Copy necessary files with verbose output
          echo "Copying files to server..."
          scp -v -r ./* ./.env ./.dockerignore root@157.180.25.1:/root/sokal-ai-generate/
          
          # Check if files were copied successfully
          echo "Verifying copied files..."
          ssh -o StrictHostKeyChecking=no root@157.180.25.1 "ls -la /root/sokal-ai-generate"
          
          # Run docker-compose on the server with debug output
          echo "Starting containers on server..."
          ssh -o StrictHostKeyChecking=no root@157.180.25.1 "cd /root/sokal-ai-generate && docker-compose down && DEBUG=* docker-compose up -d --build" 